[package]
name = "FinSc-Cosmic-Horizon"
version = "0.3.4"
ipkg = "FinSc-Cosmic-Horizon.ipkg"

[custom.all.FinSc-Multiset-Core]
type = "local"
path = "../FinSc-Multiset-Core"
ipkg = "FinSc-Multiset-Core.ipkg"

[custom.all.FinSc-Phase-Unfolding]
type = "local"
path = "../FinSc-Phase-Unfolding"
ipkg = "FinSc-Phase-Unfolding.ipkg"

[custom.all.FinSc-Geometry]
type = "local"
path = "../FinSc-Geometry"
ipkg = "FinSc-Geometry.ipkg"

[custom.all.FinSc-Thermodynamics]
type = "local"
path = "../FinSc-Thermodynamics"
ipkg = "FinSc-Thermodynamics.ipkg"
